site_name: test-drive-ai
repo_url: https://github.com/aditya02acharya/test-drive-ai
site_url: https://aditya02acharya.github.io/test-drive-ai
site_description: TestDrive AI: Business Strategy Simulator
site_author: Aditya Acharya
edit_uri: edit/main/docs/
repo_name: aditya02acharya/test-drive-ai
copyright: Maintained by <a href="https://aditya02acharya.com">aditya02acharya</a>.

nav:
  - Home: index.md
  - Modules: modules.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: ["test_drive_ai"]
theme:
  name: material
  feature:
    tabs: true
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/aditya02acharya/test-drive-ai
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/test-drive-ai

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
